from random import choice

food_diet1=[]
food_diet1.append(("白粥","200"))
food_diet1.append(("鮭魚飯糰","170"))
food_diet1.append(("雞肉飯飯糰","180"))
food_diet1.append(("21風味館香草烤雞沙拉(711)","110"))
food_diet1.append(("鰻魚玉子手卷(全家)","235"))
food_diet1.append(("蒸蛋湯","100"))
food_diet1.append(("地瓜雞胸肉沙拉餐(711)","210"))
food_diet1.append(("地瓜粥","220"))
food_diet1.append(("米粉湯","185"))
food_diet1.append(("冬粉湯","200"))
food_diet1.append(("鹽麴雞腿溫沙拉(711) ","190"))
food_diet1.append(("日式鰹節玉子手卷(全家)","195"))
food_diet1.append(("清酒蒸蛤蜊烤飯糰(全家)","182"))
food_diet1.append(("鮪魚溏心蛋三明治(全家)","190"))
food_diet1.append(("糯米腸","215"))
food_diet1.append(("豆沙包","245"))
food_diet1.append(("玉米濃湯","150"))
food_diet1.append(("肉鬆細卷(全家)","245"))
food_diet1.append(("地瓜起司三明治(711)","245"))
food_diet1.append(("港式鮮肉燒賣(全家)","200"))
food_diet1.append(("鹽可頌麵包(711)","220"))
food_diet1.append(("蛋多多雞蛋沙拉三明治(全家)","210"))
food_diet1.append(("溏心蛋筍飯飯糰(圓)(711)","170"))
food_diet1.append(("豆腐雞胸肉沙拉餐(711)","190"))
food_diet1.append(("烤豆腐溫沙拉(711)","235"))
food_diet1.append(("大飯糰鹽水雞肉(全家)","200"))
food_diet1.append(("蒲燒鰻魚烤飯糰(全家)","170"))
food_diet1.append(("石安牧場溏心蛋洋芋沙拉(711)","185"))
food_diet1.append(("壹番屋-雙起司雞肉咖哩飯糰(711)","250"))
food_diet1.append(("香檸松阪豬烤飯糰(全家)","215"))
food_diet1.append(("炙燒牛肉飯卷(全家)","295"))
food_diet1.append(("嫩雞花椰菜飯(711)","260"))
food_diet1.append(("什蔬滷味(711)","290"))
food_diet1.append(("起司火腿蛋熱壓吐司(711)","264"))
food_diet1.append(("虱目魚粥","250"))

#print(choice(food_diet))


food_diet2=[] #300-550
food_diet2.append(("鮪魚蕃茄冷義大利麵(全家)","335"))
food_diet2.append(("榨菜肉絲麵","356"))
food_diet2.append(("滷肉飯","350"))
food_diet2.append(("筒仔米糕","310"))
food_diet2.append(("刈包","500"))
food_diet2.append(("北部春捲","400"))
food_diet2.append(("雞肉飯","330"))
food_diet2.append(("蕎麥涼麵","310"))
food_diet2.append(("陽春麵","320"))
food_diet2.append(("繽紛鮮蔬烤雞便當(711)","355"))
food_diet2.append(("鮮蝦水餃10個","480"))
food_diet2.append(("皮蛋瘦肉粥","380"))
food_diet2.append(("野菇乳酪燉飯","372"))
food_diet2.append(("滑蛋肉片燴飯","515"))
food_diet2.append(("肉圓","500"))
food_diet2.append(("雞肉水餃10個","490"))
food_diet2.append(("水餃10粒","520"))
food_diet2.append(("油麵(湯)","380"))
food_diet2.append(("燻雞蔬菜鬆餅","450"))
food_diet2.append(("蚵仔煎","410"))
food_diet2.append(("魚穌羹麵","355"))
food_diet2.append(("肉燥飯","385"))
food_diet2.append(("鴨肉飯","350"))
food_diet2.append(("小炒麵","420"))
food_diet2.append(("雞絲麵","350"))
food_diet2.append(("魷魚羹麵","380"))
food_diet2.append(("肉羹米粉","360"))
food_diet2.append(("鮭魚便當","540"))
food_diet2.append(("辣炒年糕","420"))
food_diet2.append(("鍋燒烏龍麵","450"))
food_diet2.append(("餛飩麵","490"))
food_diet2.append(("丹麥鮪魚起司(711)","360"))
food_diet2.append(("鍋燒意麵","500"))
food_diet2.append(("古早味乾麵","350"))
food_diet2.append(("豬肉餡餅","325"))
food_diet2.append(("健身Ｇ肉餐盒(全家)","460"))
food_diet2.append(("清炒蒜香蛤蜊義大利麵(全家)","450"))
food_diet2.append(("小泡菜鍋","550"))
food_diet2.append(("白酒蛤蜊義大利麵","510"))
food_diet2.append(("牛肉蛋包飯","500"))
food_diet2.append(("起司玉米鬆餅","500"))
food_diet2.append(("醬油拉麵","510"))
food_diet2.append(("咖哩水餃10個","550"))
food_diet2.append(("蛋包飯","520"))
food_diet2.append(("阜杭豆漿-經典飯糰(711)","535"))
food_diet2.append(("大腸蚵仔麵線","460")


food_diet3=[] #550-800
food_diet3.append(("豬排蓋飯","795"))
food_diet3.append(("韭菜水餃10個","690"))
food_diet3.append(("油雞便當","680"))
food_diet3.append(("牛肉丼飯","691"))
food_diet3.append(("雞肉咖哩飯","670"))
food_diet3.append(("肉羹飯","750"))
food_diet3.append(("炸雞排飯","680"))
food_diet3.append(("奶油鮭魚鮮蝦義大利麵","715"))
food_diet3.append(("昆布湯鍋","620"))
food_diet3.append(("烤鴨便當","740"))
food_diet3.append(("泡菜燒肉個人小披薩","730"))
food_diet3.append(("炸醬麵","650"))
food_diet3.append(("醬燒豬肉飯","710"))
food_diet3.append(("豬排起司鬆餅","770"))
food_diet3.append(("海鮮個人小披薩","648"))
food_diet3.append(("雞肉蕃茄義大利麵","695"))
food_diet3.append(("炸蝦便當","700"))
food_diet3.append(("蝦仁蛋炒飯","700"))
food_diet3.append(("牛肉燴飯","700"))
food_diet3.append(("蔥燒牛肉飯","670"))
food_diet3.append(("肉絲蛋炒飯","720"))
food_diet3.append(("烤肉便當","670"))
food_diet3.append(("滷排骨便當","750"))
food_diet3.append(("滷大雞腿便當","800"))
food_diet3.append(("高麗菜豬肉鍋貼10個","700"))
food_diet3.append(("泡菜鍋貼10個","680"))
food_diet3.append(("牛肉丼飯","700"))
food_diet3.append(("炸豬排便當","750"))
food_diet3.append(("肉羹麵","710"))
food_diet3.append(("牛肉咖哩飯","730"))
food_diet3.append(("羊肉麵","720"))
food_diet3.append(("沙茶豬肉飯","760"))
food_diet3.append(("香腸便當","750"))
food_diet3.append(("涼麵","670"))
food_diet3.append(("蝦仁炒麵","620"))
food_diet3.append(("辣味鍋貼10個","610"))
food_diet3.append(("豚骨拉麵","620"))
food_diet3.append(("鰻魚飯便當","670"))
food_diet3.append(("酸辣湯餃","665"))
food_diet3.append(("招牌鍋貼10個","620"))
food_diet3.append(("鮪魚沙拉蔬菜","635"))
food_diet3.append(("茄汁雞肉義大利麵 ","608"))
food_diet3.append(("雞肉丼飯","635"))
food_diet3.append(("鮮蔬義大利麵","625"))
food_diet3.append(("牛肉麵","580"))
food_diet3.append(("豬肉丼飯","558"))
food_diet3.append(("海鮮豆腐鍋","580"))
food_diet3.append(("南部春捲","600"))
food_diet3.append(("麻醬麵","650"))
food_diet3.append(("番茄蝦仁義大利麵","610"))



food_breakfast1=[] #0-250
food_breakfast1.append(("鹹豆漿","185"))
food_breakfast1.append(("原味蛋餅","236"))
food_breakfast1.append(("原味貝果","240"))
food_breakfast1.append(("全麥麵包(100g)","247"))
food_breakfast1.append(("蔬菜蛋餅","250"))
food_breakfast1.append(("鮮肉包","225"))
food_breakfast1.append(("鮪魚飯糰","228"))
food_breakfast1.append(("克林姆麵包","210"))
food_breakfast1.append(("水煎包","180"))
food_breakfast1.append(("起司多穀麵包(全家)","250"))
food_breakfast1.append(("蔬菜小潛艇堡","250"))
food_breakfast1.append(("香蔥麵包","240"))
food_breakfast1.append(("果醬吐司","200"))
food_breakfast1.append(("白饅頭","220"))
food_breakfast1.append(("蔥鹽燒肉飯糰(711)","210"))
food_breakfast1.append(("鹹豆漿加蛋","250"))
food_breakfast1.append(("照燒雞溏心蛋三明治(711)","230"))
food_breakfast1.append(("起司火腿蛋三明治(711)","220"))
food_breakfast1.append(("瘋狂起司三明治(全家)","232"))
food_breakfast1.append(("地瓜乳酪麵包(全家)","220"))


food_breakfast2=[] #250-450
food_breakfast2.append(("起司蛋餅","270"))
food_breakfast2.append(("蔥抓餅","398"))
food_breakfast2.append(("鮪魚蛋餅","315"))
food_breakfast2.append(("烤煎蛋三明治","386"))
food_breakfast2.append(("燒餅夾蛋","325"))
food_breakfast2.append(("里肌蛋餅","320"))
food_breakfast2.append(("起司貝果","348"))
food_breakfast2.append(("紅豆麵包","300"))
food_breakfast2.append(("紫米飯糰","422"))
food_breakfast2.append(("燒餅","260"))
food_breakfast2.append(("叉燒包","265"))
food_breakfast2.append(("蘿蔔糕加蛋","360"))
food_breakfast2.append(("饅頭夾蛋","325"))
food_breakfast2.append(("肉鬆麵包","350"))
food_breakfast2.append(("火雞胸肉堡","280"))
food_breakfast2.append(("蔬菜蛋堡","380"))
food_breakfast2.append(("鮪魚蛋堡","420"))
food_breakfast2.append(("小籠包8個","440"))
food_breakfast2.append(("厚片吐司","300"))
food_breakfast2.append(("起司乳酪餅","440"))
food_breakfast2.append(("燻雞蛋漢堡","375"))
food_breakfast2.append(("菠蘿麵包","300"))
food_breakfast2.append(("玉米蛋餅","340"))
food_breakfast2.append(("火腿蛋吐司","280"))
food_breakfast2.append(("里肌蛋三明治","370"))
food_breakfast2.append(("鍋貼(5顆)","350"))
food_breakfast2.append(("培根蛋餅","270"))
food_breakfast2.append(("里肌墨西哥捲餅","355"))
food_breakfast2.append(("炒米粉","280"))
food_breakfast2.append(("鮪魚漢堡","380"))
food_breakfast2.append(("魚排堡","445"))
food_breakfast2.append(("培根蛋吐司","360"))
food_breakfast2.append(("里肌豬排佛卡夏","420"))
food_breakfast2.append(("火腿佛卡夏","370"))


food_breakfast3=[] #450-600
food_breakfast3.append(("起司蛋三明治","494"))
food_breakfast3.append(("蔥抓餅加蛋","480"))
food_breakfast3.append(("鮪魚潛艇堡","500"))
food_breakfast3.append(("飯糰","600"))
food_breakfast3.append(("鮪魚總匯","515"))
food_breakfast3.append(("里肌總匯","600"))
food_breakfast3.append(("香雞蛋堡","450"))
food_breakfast3.append(("卡拉雞腿蛋堡","530"))
food_breakfast3.append(("鹹飯糰加蛋","500"))
food_breakfast3.append(("燻雞總匯","560"))
food_breakfast3.append(("牛肉起司堡","460"))
food_breakfast3.append(("胡椒鐵板麵加蛋","570"))
food_breakfast3.append(("醬燒雞總匯","600"))
food_breakfast3.append(("奶酥麵包","550"))
food_breakfast3.append(("招牌總匯","580"))
food_breakfast3.append(("起司豬排蛋堡","480"))
food_breakfast3.append(("培根蛋堡","470"))
food_breakfast3.append(("青蔥肉鬆麵包","485"))
food_breakfast3.append(("醇黑可可好棒棒(全家)","530"))
food_breakfast3.append(("烤腿排佛卡夏","530"))
food_breakfast3.append(("海陸雙拼壽司組(711)","510"))
food_breakfast3.append(("丹麥菠蘿可頌(全家)","438"))
food_breakfast3.append(("沙嗲烤雞飯糰(全家)","460"))
food_breakfast3.append(("香濃牛奶好棒棒(全家)","520"))


food_big=[]
food_big.append("滷雞腿便當")
food_big.append("里肌排蛋堡+無糖豆漿")
food_big.append("雞胸肉沙拉")
food_big.append("貝果+鮮奶")
food_big.append("雞肉起司蛋堡+無糖豆漿")
food_big.append("蕎麥涼麵+沙拉")
food_big.append("鮮蝦水餃15個")
food_big.append("鰻魚飯便當 ")
food_big.append("雞肉丼飯 ")
food_big.append("牛肉丼飯")
food_big.append("饅頭夾蛋+無糖豆漿")
food_big.append("里肌總匯+鮮奶")
food_big.append("燻雞總匯+無糖紅茶")
food_big.append("烤雞潛艇堡")
food_big.append("鮮蝦潛艇堡")
food_big.append("牛肉起司蛋堡+無糖紅茶")
food_big.append("繽紛鮮蔬烤雞便當(711)+鮮奶豆漿")
food_big.append("嫩雞花椰菜飯(711)+優酪乳")
food_big.append("健身Ｇ肉餐盒(全家)+ 鮮奶豆漿")
food_big.append("清炒蒜香蛤蜊義大利麵(全家)+沙拉")
food_big.append("沙嗲烤雞飯糰(全家)+ 優酪乳")
food_big.append("鮪魚蛋堡+紅茶拿鐵")
food_big.append("鮪魚總匯+鮮奶")
food_big.append("紫米飯糰+無糖豆漿")
food_big.append("鮮蔬烤雞便當(711)+燕麥奶")


food_small=[]
food_small.append("雞肉飯飯糰")
food_small.append("里肌蛋餅")
food_small.append("燻雞蛋餅")
food_small.append("起司蛋餅")
food_small.append("起司蛋吐司")
food_small.append("里肌蛋吐司")
food_small.append("蔬菜蛋吐司")
food_small.append("茶葉蛋 +燕麥奶")
food_small.append("鮪魚飯糰")
food_small.append("番茄豆腐湯")
food_small.append("鮪魚三明治（去醬")
food_small.append("茶碗蒸 +燕麥奶")
food_small.append("烤雞三明治")
food_small.append("鮪魚蛋餅")
food_small.append("烤雞蔬菜捲")
food_small.append("雞肉水餃8個 ")
food_small.append("鮭魚飯糰")
food_small.append("雞肉飯")
food_small.append("虱目魚粥 ")
food_small.append("蔬菜蛋餅")
food_small.append("照燒雞溏心蛋三明治(711)")
food_small.append("烤煎蛋三明治")
food_small.append("起司火腿蛋熱壓吐司(711)")
food_small.append("起司多穀麵包(全家)")
food_small.append("鮪魚溏心蛋三明治(全家)")


food_fruit=[]
food_fruit.append("葡萄13顆")
food_fruit.append("棗子2顆")
food_fruit.append("蓮霧1.5顆")
food_fruit.append("柿子0.5顆")
food_fruit.append("木瓜1/3顆")
food_fruit.append("小番茄15顆")
food_fruit.append("水蜜桃1顆")
food_fruit.append("奇異果1顆")
food_fruit.append("大香蕉0.5條")
food_fruit.append("芒果0.2顆")
food_fruit.append("草莓10顆")
food_fruit.append("荔枝10顆")
food_fruit.append("橘子1顆")
food_fruit.append("蘋果1顆")
food_fruit.append("哈密瓜0.2顆")
food_fruit.append("櫻桃10顆")
food_fruit.append("李子4顆")
food_fruit.append("梨子0.5顆")
food_fruit.append("芭樂1顆")
food_fruit.append("紅西瓜1片")
food_fruit.append("柳丁1個")
food_fruit.append("金棗6個")
food_fruit.append("黃西瓜1/3個")
food_fruit.append("香瓜0.5顆")
food_fruit.append("釋迦1/2顆")
food_fruit.append("龍眼13顆")
food_fruit.append("小香蕉1條")
food_fruit.append("楊桃3/4顆")
food_fruit.append("鳳梨1/10顆")
food_fruit.append("百香果2顆")
food_fruit.append("白火龍果1/4顆")
food_fruit.append("紅火龍果1/4顆")

